1. two_layer_neural_net

In [ ]:
from __future__ import print_function
import torch

In [ ]:
x = torch.empty(5,3)
print(x)

tensor([[1.0081e-37, 3.0712e-41, 2.3694e-38],
        [9.2196e-41, 1.1578e+27, 1.1362e+30],
        [7.1547e+22, 4.5828e+30, 1.2121e+04],
        [7.1846e+22, 9.2198e-39, 7.0374e+22],
        [2.0474e-38, 0.0000e+00, 0.0000e+00]])


In [ ]:
x = torch.rand(5,3)
x

tensor([[0.3243, 0.0489, 0.5055],
        [0.8653, 0.2405, 0.8032],
        [0.8530, 0.4088, 0.9892],
        [0.1252, 0.3586, 0.2395],
        [0.1731, 0.4854, 0.5309]])

In [ ]:
x = torch.zeros(5, 3, dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [ ]:
x = torch.tensor([5.5, 3])
x

tensor([5.5000, 3.0000])

In [ ]:
x = x.new_ones(5, 3, dtype=torch.double)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [ ]:
x = torch.randn_like(x, dtype=torch.float64)
x

tensor([[-0.5515, -0.8704, -0.9437],
        [-1.2185, -2.1508, -0.9661],
        [ 0.9058,  1.4730, -1.2416],
        [-0.2998,  1.0787,  0.2308],
        [-1.5377, -0.1582,  0.3396]], dtype=torch.float64)

In [ ]:
x.size()

torch.Size([5, 3])

In [ ]:
y = torch.rand(5, 3)
y

tensor([[0.5726, 0.2521, 0.7942],
        [0.8552, 0.0592, 0.8101],
        [0.6558, 0.4032, 0.0982],
        [0.8008, 0.9397, 0.6803],
        [0.8778, 0.9382, 0.5820]])

In [ ]:
x + y

tensor([[ 0.0212, -0.6183, -0.1494],
        [-0.3634, -2.0915, -0.1559],
        [ 1.5616,  1.8762, -1.1434],
        [ 0.5010,  2.0184,  0.9112],
        [-0.6598,  0.7800,  0.9216]], dtype=torch.float64)

In [ ]:
torch.add(x, y)

tensor([[ 0.0212, -0.6183, -0.1494],
        [-0.3634, -2.0915, -0.1559],
        [ 1.5616,  1.8762, -1.1434],
        [ 0.5010,  2.0184,  0.9112],
        [-0.6598,  0.7800,  0.9216]], dtype=torch.float64)

In [ ]:
y.add_(x)
y

tensor([[ 0.0212, -0.6183, -0.1494],
        [-0.3634, -2.0915, -0.1559],
        [ 1.5616,  1.8762, -1.1434],
        [ 0.5010,  2.0184,  0.9112],
        [-0.6598,  0.7800,  0.9216]])

In [ ]:
x = torch.rand(4,4)
x

tensor([[0.9595, 0.2588, 0.3359, 0.2219],
        [0.0817, 0.6863, 0.7256, 0.7820],
        [0.6722, 0.3059, 0.1123, 0.2775],
        [0.7257, 0.1293, 0.1969, 0.6495]])

In [ ]:
y = x.view(16)
y

tensor([0.9595, 0.2588, 0.3359, 0.2219, 0.0817, 0.6863, 0.7256, 0.7820, 0.6722,
        0.3059, 0.1123, 0.2775, 0.7257, 0.1293, 0.1969, 0.6495])

In [ ]:
z = x.view(-1, 8)
z

tensor([[0.9595, 0.2588, 0.3359, 0.2219, 0.0817, 0.6863, 0.7256, 0.7820],
        [0.6722, 0.3059, 0.1123, 0.2775, 0.7257, 0.1293, 0.1969, 0.6495]])

In [ ]:
x = torch.randn(2)
print(x)
print(x[0].item())
print(x.numpy())

tensor([-0.1474, -0.9406])
-0.14738886058330536
[-0.14738886 -0.9406434 ]


In [ ]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
print(torch.cuda.is_available())
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

False


In [ ]:
import numpy as np

N, D_in, H, D_out = 64, 1000, 100, 10

x = np.random.randn(N, D_in)
y = np.random.randn(N, D_out)

w1 = np.random.randn(D_in, H)
w2 = np.random.randn(H, D_out)

learning_rate = 1e-6

for t in range(500):
  h = x.dot(w1)
  h_relu = np.maximum(h, 0)
  y_pred = h_relu.dot(w2)

  loss = np.square(y_pred - y).sum()
  print(f't {t}, loss {loss}')

  # Backprop to compute gradients of w1 and w2 with respect to loss
    
  # loss = (y_pred - y) ** 2
  grad_y_pred = 2.0 * (y_pred - y)
  # 
  grad_w2 = h_relu.T.dot(grad_y_pred)
  grad_h_relu = grad_y_pred.dot(w2.T)
  grad_h = grad_h_relu.copy()
  grad_h[h < 0] = 0
  grad_w1 = x.T.dot(grad_h)

  # Update weights
  w1 -= learning_rate * grad_w1
  w2 -= learning_rate * grad_w2

In [ ]:
import torch


class TwoLayerNet(torch.nn.Module):
    def __init__(self, D_in, H, D_out):
        """
        In the constructor we instantiate two nn.Linear modules and assign them as
        member variables.
        """
        super(TwoLayerNet, self).__init__()
        self.linear1 = torch.nn.Linear(D_in, H)
        self.linear2 = torch.nn.Linear(H, D_out)

    def forward(self, x):
        """
        In the forward function we accept a Tensor of input data and we must return
        a Tensor of output data. We can use Modules defined in the constructor as
        well as arbitrary operators on Tensors.
        """
        h_relu = self.linear1(x).clamp(min=0)
        y_pred = self.linear2(h_relu)
        return y_pred


# N is batch size; D_in is input dimension;
# H is hidden dimension; D_out is output dimension.
N, D_in, H, D_out = 64, 1000, 100, 10

# Create random Tensors to hold inputs and outputs
x = torch.randn(N, D_in)
y = torch.randn(N, D_out)

# Construct our model by instantiating the class defined above
model = TwoLayerNet(D_in, H, D_out)

# Construct our loss function and an Optimizer. The call to model.parameters()
# in the SGD constructor will contain the learnable parameters of the two
# nn.Linear modules which are members of the model.
criterion = torch.nn.MSELoss(reduction='sum')
optimizer = torch.optim.SGD(model.parameters(), lr=1e-4)
for t in range(500):
    # Forward pass: Compute predicted y by passing x to the model
    y_pred = model(x)

    # Compute and print loss
    loss = criterion(y_pred, y)
    print(t, loss.item())

    # Zero gradients, perform a backward pass, and update the weights.
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

0 654.0119018554688
1 605.621826171875
2 563.7447509765625
3 526.8578491210938
4 493.9427490234375
5 464.1705322265625
6 437.1316223144531
7 412.3821716308594
8 389.62982177734375
9 368.568115234375
10 348.8327941894531
11 330.46356201171875
12 313.23577880859375
13 296.88067626953125
14 281.3717956542969
15 266.6604919433594
16 252.79090881347656
17 239.5773162841797
18 226.99203491210938
19 214.96719360351562
20 203.4740447998047
21 192.4944610595703
22 182.06686401367188
23 172.1697998046875
24 162.7066650390625
25 153.6932830810547
26 145.09799194335938
27 136.92520141601562
28 129.15115356445312
29 121.77545166015625
30 114.77500915527344
31 108.13796997070312
32 101.85194396972656
33 95.92078399658203
34 90.32894897460938
35 85.0599365234375
36 80.09194946289062
37 75.40869903564453
38 70.99629974365234
39 66.84492492675781
40 62.93670654296875
41 59.25718688964844
42 55.79793930053711
43 52.549442291259766
44 49.493629455566406
45 46.62544631958008
46 43.93473434448242
47 41.408